### ISSUE TITLE
Some ideas about large tilt angle to cross narrow gaps 

### ISSUE THREAD

**Issue by GChasing** [ZJU-FAST-Lab/GCOPTER#11]
@ZhepeiWang Thanks a lot. I found some associted code about gcopter at https://github.com/ZJU-FAST-Lab/Fast-Racing/blob/a1d086ccb6deb2993d71a5afda13fffa66567363/src/plan_manage/src/MinCoPlan_CPU.cpp#L117 - https://github.com/ZJU-FAST-Lab/Fast-Racing/blob/a1d086ccb6deb2993d71a5afda13fffa66567363/src/plan_manage/src/MinCoPlan_CPU.cpp#L124. 

It is a huge project, which may be unfriendly to the newer.  Could you share some ideas about how to show the large tilt angle 
to crosse narrow gaps, and how to insert the waypoints in the #9 (Adding the waypoints)?

Thanks again, and wish your reply!

**Comment by ZhepeiWang** [comment]
Yeah I fully understand your concern. Admittedly some projects related to this repo maybe too huge to be portably used. That's exactly the reason why this repo was intended to provide some clean and small demo or example. Unfortunately, things just got a bit out of hand as I had a full-time job. I'm not sure when I have time to finish example 2, 3 or 4 for many tasks. I suggest you to read these projs instead of waiting for the possible clean and friendly code in the future. Sorry for being busy for quite a long time.

**Comment by GChasing** [comment]
Thank you again. I will take your suggestions and continue to pay attention to the subsequent updates of this repo.
