### ISSUE TITLE
Formation Keeping Planning

### ISSUE THREAD

**Issue by 001zwzwzw** [ZJU-FAST-Lab/GCOPTER#2]
hello!  I want to ask that do you like to publish the source of Formation Keeping Planning? wether you have the test in real UAV?
Thanks for your answer!

**Comment by ZhepeiWang** [comment]
The source code of formation keeping is another project powered by this traj optimizer. Please refer to the repo:
https://github.com/ZJU-FAST-Lab/Swarm-Formation

This repo is only for the optimizer and its various examples. I am not sure whether I will give a example for the formation. 
Even if so, it will be a couple of weeks later since I have many DDLs recently. But you will definitely find the source you want in the above-mentioned repo, which should be released before ICRA 2022 conference. Or you can push @SamuraiChamploo to release their source LOL

**Comment by 001zwzwzw** [comment]
@ZhepeiWang thanks! I hope they can publish their source since these achievements are so good.I want to learn more from them!
