### ISSUE TITLE
The code seems not work in the free space (no obstacles information)

### ISSUE THREAD

**Issue by Zyhlibrary** [ZJU-FAST-Lab/GCOPTER#6]
Hi, when i use the code in our own environment, the code always meets the error in the part of convexCover if there are no obstacles info around the route. Is there a bug in the code or just caused by our incorrect using?

**Comment by ZhepeiWang** [comment]
It seems to be a corner case that is not well handled. 
Could you please provide the input information of convexCover?
The inputs are: 
const std::vector<Eigen::Vector3d> &**path**,
const std::vector<Eigen::Vector3d> &**points**,
const Eigen::Vector3d &**lowCorner**,
const Eigen::Vector3d &**highCorner**,
const double &**progress**,
const double &**range**

**Comment by Zyhlibrary** [comment]
![Screenshot from 2022-05-19 14-03-19](https://user-images.githubusercontent.com/58259821/169222043-f0b913de-e345-4c2f-9153-295e463a2df8.png)
Thanks for your reply. The path and the obstacle points are shown in the figure. The lowCorner: (-20,-20,0) highCorner: (20,20,2),progress: 7, range: 3. The error occurred in the function firi::firi(bd, pc, a, b, hp)
![Screenshot from 2022-05-19 14-14-00](https://user-images.githubusercontent.com/58259821/169223151-552f3f52-6509-4f8d-a309-d686ee0353f3.png)
;

**Comment by Zyhlibrary** [comment]
Actually, once the environment has no obstacles, the obstacle points will be empty,  it should be easier to build the flight corridor and get the optimal path, but the code seems not work in this case. I guess there are no constraint on the maximum construction range when build the flight corridor in the environment without obstacles.

**Comment by ZhepeiWang** [comment]
I wonder if there is a call where pc contained no points.
If this is the truth, it can be simply resolved by return the bd with normalized normal vectors.
Could you print valid_pc.size() before the call to firi::firi? Or I will do the test later.

**Comment by Zyhlibrary** [comment]
valid_pc: 2108
valid_pc: 418
valid_pc: 125
valid_pc: 0
This is the results in one construction process.

**Comment by ZhepeiWang** [comment]
I have found a bug when no obstacles exist which is caused by distRs.minCoeff(&pcMinId)
When pc is empty, distRs is also an empty vec.
In Eigen, find the minimum element in an empty vec causes crashes.

I have fixed it in [the commit](https://github.com/ZJU-FAST-Lab/GCOPTER/commit/081944d1b44bf7d4678ac271ce9e92305dafc2e9).
Please check it in your case and see if it solves your problem. 
Whether it works or not, please tell me the results.

**Comment by Zyhlibrary** [comment]
It perfectly solves the problem. Thanks for your time and detailed explanation~

**Comment by ZhepeiWang** [comment]
I have found a bug when no obstacles exist which is caused by distRs.minCoeff(&pcMinId)
When pc is empty, distRs is also an empty vec.
In Eigen, find the minimum element in an empty vec causes crashes.

I have fixed it in the [commit.](https://github.com/ZJU-FAST-Lab/GCOPTER/commit/b5d1dd17a0b2a1106e7ba321b4f483f363f5b6f9)

Please check it in your case and see if it solves your problem.
Whether it works or not, please tell me the results.

**Comment by ZhepeiWang** [comment]
> It perfectly solves the problem. Thanks for your time and detailed explanation~

Hey, I made a typo in an old commit but some how it hides the crash. 

Please check the commit mentioned above.

**Comment by ZhepeiWang** [comment]
![0](https://user-images.githubusercontent.com/8651775/169244284-468ae555-1f40-4521-bbbf-fff0c0a347a9.png)
The typos are fixed now.

**Comment by Zyhlibrary** [comment]
OK, thanks for that, it also works. hhh~
